# Generated by Django 4.2.20 on 2025-06-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_readingpassage_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingpassage',
            name='identifier',
            field=models.CharField(default='a', help_text='Passage identifier (a, b, c)', max_length=1),
        ),
    ]
