# Generated by Django 4.2.20 on 2025-06-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_listeningquestion_listeninguseranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningquestion',
            name='level',
            field=models.CharField(choices=[('4', 'Grade 4'), ('3', 'Grade 3'), ('2', 'Grade 2'), ('1', 'Grade 1'), ('pre1', 'Pre-Grade 1')], default='4', max_length=10),
        ),
    ]
