# Generated by Django 4.2.20 on 2025-06-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_listeningchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeningquestion',
            name='audio',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
