# Generated by Django 4.2.20 on 2025-06-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_alter_listeningquestion_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningquestion',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
