# Generated by Django 4.2.20 on 2025-06-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_listeningquestion_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingquestion',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
