# Generated by Django 4.2.20 on 2026-07-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_readingquestion_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grammarfillquestion',
            name='level',
            field=models.CharField(choices=[('5', 'Grade 5'), ('4', 'Grade 4'), ('3', 'Grade 3'), ('2', 'Grade 2'), ('1', 'Grade 1'), ('pre1', 'Pre-Grade 1')], default='4', max_length=10),
        ),
        migrations.AlterField(
            model_name='listeningquestion',
            name='level',
            field=models.CharField(choices=[('5', 'Grade 5'), ('4', 'Grade 4'), ('3', 'Grade 3'), ('2', 'Grade 2'), ('1', 'Grade 1'), ('pre1', 'Pre-Grade 1')], default='4', max_length=10),
        ),
        migrations.AlterField(
            model_name='readingpassage',
            name='level',
            field=models.CharField(choices=[('5', 'Grade 5'), ('4', 'Grade 4'), ('3', 'Grade 3'), ('2', 'Grade 2'), ('1', 'Grade 1'), ('pre1', 'Pre-Grade 1')], default='4', max_length=10),
        ),
    ]
