# Generated by Django 4.2.20 on 2026-08-12 22:42

from django.db import migrations, models


def block_all_existing_content(apps, schema_editor):
    """既存の読解・リスニングは削除せず blocked にし、公開面から外す。"""
    ListeningQuestion = apps.get_model('questions', 'ListeningQuestion')
    ReadingPassage = apps.get_model('questions', 'ReadingPassage')
    ListeningQuestion.objects.all().update(provenance='blocked')
    ReadingPassage.objects.all().update(provenance='blocked')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_add_grade5_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeningquestion',
            name='provenance',
            field=models.CharField(
                choices=[
                    ('original', 'オリジナル（公開可）'),
                    ('blocked', '非公開（公式由来など）'),
                ],
                db_index=True,
                default='original',
                help_text='original=公開可 / blocked=公開しない（削除せず保持）',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='readingpassage',
            name='provenance',
            field=models.CharField(
                choices=[
                    ('original', 'オリジナル（公開可）'),
                    ('blocked', '非公開（公式由来など）'),
                ],
                db_index=True,
                default='original',
                help_text='original=公開可 / blocked=公開しない（削除せず保持）',
                max_length=20,
            ),
        ),
        migrations.RunPython(block_all_existing_content, noop_reverse),
    ]
