# Generated by Django 4.2.20 on 2026-09-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_provenance_default_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingquestion',
            name='study_points',
            field=models.JSONField(blank=True, help_text='学習ポイント（category / title / keys のdict）。ノート・振り返り用', null=True),
        ),
    ]
