# Generated by Django 4.2.20 on 2025-04-13 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20250413_2233'),
    ]

    operations = [
    ]
