# Generated by Django 4.2.20 on 2026-08-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_exam_level',
            field=models.CharField(blank=True, default='', help_text='問題一覧で最後に選んだ級（5 / 4 / 3）。ログイン後の表示に使う。', max_length=10),
        ),
    ]
