# Generated by Django 4.2.20 on 2026-09-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_preferred_exam_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='recovery_code_hash',
            field=models.CharField(
                blank=True,
                default='',
                help_text='パスワード再設定用の復元コード（ハッシュ保存）。平文は保存しない。',
                max_length=128,
            ),
        ),
    ]
