# Generated by Django 4.2.20 on 2025-04-16 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200, verbose_name='選択肢')),
                ('is_correct', models.BooleanField(default=False, verbose_name='正解')),
                ('order', models.IntegerField(default=0, verbose_name='表示順')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[('4', 'Grade 4')])),
                ('question_type', models.CharField(choices=[('grammar_fill', '文法空所補充'), ('conversation_fill', '会話文空所補充'), ('word_order', '語句整序'), ('reading_comprehension', '長文読解'), ('listening_response', 'リスニング第1部: 応答選択'), ('listening_conversation', 'リスニング第2部: 会話内容一致'), ('listening_short_passage', 'リスニング第3部: 短文内容一致')], max_length=50)),
                ('question_text', models.TextField()),
                ('listening_text', models.TextField(blank=True, help_text='リスニング問題の音声内容', null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exams.question'),
        ),
    ]
