# Generated by Django 4.2.20 on 2025-04-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('grammar', '文法問題'), ('conversation', '会話問題'), ('word_order', '語順整序'), ('reading', '読解問題'), ('listening_response', 'リスニング応答問題'), ('listening_conversation', 'リスニング会話問題'), ('listening_short_passage', 'リスニング短文問題')], max_length=50),
        ),
    ]
