# Generated by Django 4.2.20 on 2025-04-16 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={'ordering': ['-answered_at']},
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='created_at',
            new_name='answered_at',
        ),
    ]
