# Generated by Django 4.2.20 on 2025-04-16 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_useranswer_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='choice',
            new_name='selected_choice',
        ),
    ]
