# Generated by Django 4.2.20 on 2025-04-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_userprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(max_length=50),
        ),
    ]
