# Generated by Django 4.2.20 on 2025-05-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_question_passage'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='identifier',
            field=models.CharField(blank=True, help_text='本文の識別子（a, bなど）または問題の識別子（a1, b1など）', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('grammar', '文法'), ('vocabulary', '語彙'), ('reading_comprehension', '長文読解'), ('reading_passage', '長文読解本文'), ('listening_response', 'リスニング応答問題'), ('listening_conversation', 'リスニング会話問題'), ('listening_short_passage', 'リスニング短文問題'), ('listening_illustration', 'リスニングイラスト問題')], max_length=50),
        ),
    ]
