# Generated by Django 4.2.20 on 2025-05-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_question_identifier_alter_question_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_file',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='image_file',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('4', 'Grade 4'), ('3', 'Grade 3'), ('2', 'Grade 2'), ('1', 'Grade 1'), ('pre1', 'Pre-Grade 1')], max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('grammar', '文法'), ('vocabulary', '語彙'), ('reading_comprehension', '長文読解'), ('reading_passage', '長文読解本文'), ('listening_illustration', 'リスニング第1部: イラスト問題'), ('listening_question', 'Listening Question'), ('reading_question', 'Reading Question')], max_length=50),
        ),
    ]
