# Generated by Django 4.2.20 on 2025-05-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_question_audio_file_question_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(default=1),
        ),
    ]
