# Generated by Django 4.2.20 on 2025-06-04 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_grammarfillquestion_grammarfillchoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0011_question_question_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('reading_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.readingquestion')),
                ('selected_reading_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.readingchoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-answered_at'],
            },
        ),
    ]
