# Generated by Django 4.2.20 on 2025-06-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_readinguseranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('grammar', '文法'), ('vocabulary', '語彙'), ('reading_comprehension', '長文読解'), ('reading_passage', '長文読解本文'), ('listening_illustration', 'リスニング第1部: イラスト問題'), ('listening_conversation', 'リスニング第2部: 会話問題'), ('listening_question', 'Listening Question'), ('reading_question', 'Reading Question')], max_length=50),
        ),
    ]
