# Generated by Django 4.2.20 on 2025-06-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_alter_question_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='試験タイトル')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('exam_type', models.CharField(choices=[('regular', '通常問題'), ('listening', 'リスニング問題')], default='regular', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('grammar_fill', '文法・語彙問題'), ('conversation_fill', '会話補充問題'), ('word_order', '語順選択問題'), ('reading_comprehension', '長文読解問題'), ('listening_passage', 'リスニング第3部: 文章問題'), ('listening_illustration', 'リスニング第2部: イラスト問題'), ('listening_conversation', 'リスニング第1部: 会話問題')], max_length=50),
        ),
    ]
