# Generated by Django 4.2.20 on 2025-06-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0016_alter_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('grammar_fill', '文法・語彙問題'), ('conversation_fill', '会話補充問題'), ('word_order', '語順選択問題'), ('reading_comprehension', '長文読解問題'), ('listening_conversation', 'リスニング第2部: 会話問題'), ('listening_illustration', 'リスニング第1部: イラスト問題'), ('listening_passage', 'リスニング第3部: 文章問題')], max_length=50),
        ),
    ]
