# Generated by Django 4.2.20 on 2025-07-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprogress',
            name='level',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='level',
            field=models.CharField(max_length=10),
        ),
    ]
