# Generated by Django 4.2.20 on 2025-10-28 08:22

from django.db import migrations
import pytz
from django.utils import timezone


def fix_timezone_data(apps, schema_editor):
    """既存のnaive datetimeを日本時間のaware datetimeに変換"""
    UserProgress = apps.get_model('exams', 'UserProgress')
    UserAnswer = apps.get_model('exams', 'UserAnswer')
    ReadingUserAnswer = apps.get_model('exams', 'ReadingUserAnswer')
    
    # 日本時間のタイムゾーン
    jst = pytz.timezone('Asia/Tokyo')
    
    # UserProgressのlast_attemptedを修正
    for progress in UserProgress.objects.all():
        if progress.last_attempted and progress.last_attempted.tzinfo is None:
            # naive datetimeを日本時間として扱い、aware datetimeに変換
            progress.last_attempted = jst.localize(progress.last_attempted)
            progress.save()
    
    # UserAnswerのanswered_atを修正
    for answer in UserAnswer.objects.all():
        if answer.answered_at and answer.answered_at.tzinfo is None:
            answer.answered_at = jst.localize(answer.answered_at)
            answer.save()
    
    # ReadingUserAnswerのanswered_atを修正
    for answer in ReadingUserAnswer.objects.all():
        if answer.answered_at and answer.answered_at.tzinfo is None:
            answer.answered_at = jst.localize(answer.answered_at)
            answer.save()


def reverse_fix_timezone_data(apps, schema_editor):
    """逆操作（必要に応じて）"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0020_alter_dailyprogress_level_alter_userprogress_level'),
    ]

    operations = [
        migrations.RunPython(fix_timezone_data, reverse_fix_timezone_data),
    ]