# Generated by Django 4.2.20 on 2026-06-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0024_user_streak_and_badge'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='writing_rubric',
            field=models.JSONField(blank=True, help_text='ライティング自己チェック用ルーブリック（登録時に問題文から抽出）', null=True),
        ),
        migrations.AddField(
            model_name='writinguseranswer',
            name='feedback_json',
            field=models.JSONField(blank=True, help_text='Phase-1 自己チェック結果（語数・文数など）', null=True),
        ),
    ]
