# Generated by Django 4.2.20 on 2026-07-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0025_writing_rubric_and_feedback_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('5', 'Grade 5'), ('4', 'Grade 4'), ('3', 'Grade 3'), ('2', 'Grade 2'), ('1', 'Grade 1'), ('pre1', 'Pre-Grade 1')], max_length=10),
        ),
    ]
