# Generated by Django 4.2.20 on 2026-08-06 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0026_add_grade5_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='speaking_data',
            field=models.JSONField(blank=True, help_text='スピーキング用（title / passage / questions）', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('grammar_fill', '文法・語彙問題'), ('conversation_fill', '会話補充問題'), ('word_order', '語順選択問題'), ('reading_comprehension', '長文読解問題'), ('writing', 'ライティング問題'), ('speaking', 'スピーキング問題'), ('listening_conversation', 'リスニング第2部: 会話問題'), ('listening_illustration', 'リスニング第1部: イラスト問題'), ('listening_passage', 'リスニング第3部: 文章問題')], max_length=50),
        ),
        migrations.CreateModel(
            name='SpeakingUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_json', models.JSONField(blank=True, help_text='任意のテキスト回答 {"q1": "...", "q2": "...", "q3": "..."}', null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-answered_at'],
            },
        ),
    ]
