# Generated by Django 4.2.20 on 2026-08-12 22:42

from django.db import migrations, models


def block_all_existing_questions(apps, schema_editor):
    """既存問題は削除せず blocked にし、公開面から外す。"""
    Question = apps.get_model('exams', 'Question')
    Question.objects.all().update(provenance='blocked')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0027_add_speaking_question_type_and_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='provenance',
            field=models.CharField(
                choices=[
                    ('original', 'オリジナル（公開可）'),
                    ('blocked', '非公開（公式由来など）'),
                ],
                db_index=True,
                default='original',
                help_text='original=公開可 / blocked=公開しない（削除せず保持）',
                max_length=20,
            ),
        ),
        migrations.RunPython(block_all_existing_questions, noop_reverse),
    ]
