# Generated by Django 4.2.20 on 2026-08-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0028_add_provenance_and_block_existing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='provenance',
            field=models.CharField(choices=[('original', 'オリジナル（公開可・明示したもののみ）'), ('blocked', '非公開（既存・未確認・取り込み含む）')], db_index=True, default='blocked', help_text='公開は original のみ。既定は blocked（明示した新規自作だけ original）', max_length=20),
        ),
    ]
