# Generated by Django 4.2.20 on 2026-08-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0029_provenance_default_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='study_points',
            field=models.JSONField(blank=True, help_text='学習ポイント（category / title / keys のdict）。ノート・振り返り用', null=True),
        ),
    ]
